name: gaussian_splatting
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.8  # Upgrade to avoid compatibility issues
  - pip
  - cudatoolkit=11.8  # Matches official PyTorch compatibility
  - pytorch=2.1.0+cu118  # Newer stable PyTorch version
  - torchvision=0.16.0+cu118  # Compatible with PyTorch 2.0
  - torchaudio=2.1.0+cu118
  - plyfile
  - tqdm
  - tbb  # Fixes Intel TBB missing symbol error
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
    - submodules/fused-ssim
    - opencv-python
    - joblib
